title        = "THINKING MEGANE"
baseurl      = "https://blog.monochromegane.com"
languageCode = "ja-jp"

[permalinks]
  post = "/blog/:year/:month/:day/:filename/"

[params]
  Twitter   = "monochromegane"
  GitHub    = "monochromegane"
  Analytics = "UA-38374674-1"
  AuthorName = "monochromegane"
  AuthorBio  = [
    "monochromegane (モノクロめがね) と申します。",
    "最近はもっぱらGoに夢中です。普段は研究開発をやっています。"
  ]
  Description = "THINKING MEGANE"
